Add in commands like gg, G, L, M, H, f, r, R
tauraamui/lilly pull request #218
Opened 2024-10-27 04:35 UTC by wilsonk

Adding back in these commands. Trying out adding a branch to the main Lilly repo also.  Tests work and my manual testing works also.

2024-10-27 12:28 UTC, tauraamui commented on src/view.v
> +	g_count                   int
Please `g_count` and `z_count` fields to the type `ViewLeaderState`. I do not like __I actually hate it__ the name `ViewLeaderState` as its not technically correct because it doesn't just contain counts related to leader based invocation, but its better for now that leaving the fields in the root view struct.

2024-10-27 12:30 UTC, tauraamui commented on src/view.v
> +	view.d_count = 0
Please add these resets to `func (mut state ViewLeaderState) reset()` method on line152

2024-10-27 12:35 UTC, tauraamui commented on src/view.v
> +		view.leader_state.mode = .normal
This is redundant, escape invokes `leader_state.reset()` which resets `mode` back to `.normal`.

2024-10-27 16:25 UTC, tauraamui commented on src/view.v
> +	view.clamp_cursor_x_pos()
```suggestion
        mut repeat_amount := strconv.atoi(view.chord.pending_repeat_amount()) or { 0 }
	view.g_count += 1
	match view.leader_state.mode {
	        .normal {
	                if view.g_count == 1 { view.leader_state.mode = .pending_g } 
	        }
	        .pending_g {
	                if view.g_count >= 2 {
	                        repeat_amount -= 1
	                        if repeat_amount < 0 { repeat_amount = 0 }
	                        view.jump_cursor_to(repeat_amount)
	                        view.chord.reset() 
	                }
	        }
	}
	view.leader_state.reset()
	view.clamp_cursor_x_pos()
```

2024-10-27 16:27 UTC, tauraamui commented on src/view_keybinds.v
> +						view.shift_l()
Leave it for now, but we need to change all instances of us using this 1 dimensional if statement either into a positive condition returns or a match.

2024-10-27 16:29 UTC, tauraamui requested changes
TSM! Please view my comments/suggestions and let me know if you have any concerns or questions at all, to continue the discussion! :)

2024-10-28 00:34 UTC, wilsonk commented on src/view.v
> +	g_count                   int
No problems, I basically just re-commited the old diff for these movements and I didn't really look into ViewLeaderState usage. Looks better. Changes made for all of g,z,d,f _count variables.

2024-10-28 00:35 UTC, wilsonk commented on src/view.v
> +	view.d_count = 0
Right, I see the reset function does what is needed for all these cases I originally just zeroed locally. Changed all occurances to reset().

2024-10-28 00:35 UTC, wilsonk commented on src/view.v
> +		view.leader_state.mode = .normal
Got it, change as per previous comment.

2024-10-28 00:38 UTC, wilsonk commented on src/view.v
> +	view.clamp_cursor_x_pos()
Interestingly this was already changed in my branch? Anyways, it looks correct now for all the f,g,G occurrences now. Will push changes post-haste :)

2024-10-28 00:39 UTC, wilsonk commented on src/view_keybinds.v
> +						view.shift_l()
Right, and we should also change over all the key_binds to use chords, as previously suggested.

2024-10-28 01:09 UTC, tauraamui commented on src/view.v
> +	view.clamp_cursor_x_pos()
Weird, I only raised it as a suggestion and didn't tell it to apply it. Sorry!

2024-10-28 01:10 UTC, tauraamui commented on src/view_keybinds.v
> +						view.shift_l()
Yeah that too. But we're in the death to else case cult here! :3 #noelseorelse

2024-10-28 01:12 UTC, tauraamui commented on src/view.v
> +	if view.leader_state.d_count == 1 || view.leader_state.z_count == 1 || view.leader_state.mode == .replace || view.leader_state.g_count == 1 || view.leader_state.f_count == 1 || view.leader_state.mod
Dw about it for now but I think this needs some re-thinking, it's getting kind of long.

2024-10-28 02:14 UTC, merged